soft_uni_blog:
    resource: "@SoftUniBlogBundle/Controller/"
    type:     annotation
    prefix:   /


# These first lines load the all routes defined as @Route() annotations in any
# controller defined inside the src/AppBundle/Controller/ directory. Controllers
# are loaded recursively, so you can separate them into subdirectories.
# If you don't like to add annotations in your applications, you can also define
# the routes in YAML, XML or PHP files.
# See http://symfony.com/doc/current/book/routing.html

# These lines define a route using YAML configuration. The controller used by
# the route (FrameworkBundle:Template:template) is a convenient shortcut when
# the template can be rendered without executing any logic in your own controller.
# See http://symfony.com/doc/current/cookbook/templating/render_without_controller.html

SoftUniBlogBundle_comment_new:
    path:  /new/{article_id}
    defaults: { _controller: SoftUniBlogBundle:Comment:new}
    requirements:
        method:  GET
        article_id: \d+


SoftUniBlogBundle_comment_create:
        path:  /comment/{article_id}
        defaults: { _controller: SoftUniBlogBundle:Comment:create }
        requirements:
            method:  POST
            article_id: \d+
